"""Run inside the API container. Uses disposable SQL schema + Mongo database.

No existing users, campaigns or telemetry are changed. Cleanup only names
generated by this process, even on failure.
"""
import asyncio
import json
import re
from uuid import uuid4
from datetime import datetime, timedelta, timezone
from httpx import AsyncClient, ASGITransport
from sqlalchemy import text, select, func
from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker
from app.config import settings
from app.db import Base, get_db
from app.main import create_app
from app.models import User, AdClickReceipt, AdBudgetLedger
from app.mongo import get_client, get_mongo, ensure_indexes


async def main():
    name = "qa_mmoe_" + uuid4().hex
    assert re.fullmatch(r"qa_mmoe_[a-f0-9]{32}", name)
    admin_engine = create_async_engine(settings.database_url)
    async with admin_engine.begin() as connection:
        await connection.execute(text(f'CREATE SCHEMA "{name}"'))
    engine = create_async_engine(settings.database_url, connect_args={"server_settings": {"search_path": name}})
    sessions = async_sessionmaker(engine, expire_on_commit=False)
    original_mongo = settings.mongo_db
    settings.mongo_db = name
    async def database():
        async with sessions() as session:
            yield session
    app = create_app()
    app.dependency_overrides[get_db] = database
    try:
        async with engine.begin() as connection:
            await connection.run_sync(Base.metadata.create_all)
        await ensure_indexes()
        async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
            async def call(method, url, headers=None, **kwargs):
                response = await client.request(method, url, headers=headers, **kwargs)
                assert response.status_code < 300, (method, url, response.status_code, response.text)
                return response.json()
            async def account(label, gender, role="viewer"):
                data = await call("POST", "/auth/register", json={"email": f"{label}@example.com", "password": "testing123", "display_name": label,
                                                                "gender": gender, "role": role})
                return {"Authorization": "Bearer " + data["access_token"]}, data["user"]
            advertiser, owner = await account("advertiser", "unspecified", "advertiser")
            woman, wu = await account("woman", "woman")
            woman2, wu2 = await account("woman2", "woman")
            man, mu = await account("man", "man")
            unknown, uu = await account("unknown", "unspecified")
            video = await call("POST", "/videos", advertiser, data={"title": "QA ad", "category": "ciencia"})
            for i in range(8):
                await call("POST", "/videos", advertiser, data={"title": f"QA organic {i}", "category": "musica"})
            campaign = await call("POST", "/campaigns", advertiser, json={"name": "QA clicks", "bid_cents": 60,
                "daily_budget_cents": 100, "video_id": video["id"], "landing_url": "https://example.com/qa", "targeting_genders": ["woman"]})
            for headers in (man, unknown):
                feed = await call("GET", "/feed?session_id=s", headers)
                assert not any(i["kind"] == "ad" for i in feed["items"])
            exp_ids = []
            for headers in (woman, woman2):
                feed = await call("GET", "/feed?session_id=s", headers)
                item = next(i for i in feed["items"] if i["kind"] == "ad")
                assert item["landing_url"] == "https://example.com/qa"
                eid = str(uuid4()); exp_ids.append(eid)
                payload = {"exposure_id": eid, "decision_id": item["decision_id"], "video_id": item["video_id"], "session_id": "s"}
                await asyncio.gather(*[call("POST", "/exposures", headers, json=payload) for _ in range(2)])
                play = {"event_id": str(uuid4()), "exposure_id": eid, "session_id": "s", "video_id": item["video_id"], "event_type": "play"}
                await call("POST", "/events", headers, json={"events": [play, play]})
                feed2 = await call("GET", "/feed?session_id=s", headers)
                assert not any(i["kind"] == "ad" for i in feed2["items"])
            # Two users + duplicate requests race for a single billable click.
            responses = await asyncio.gather(*[call("POST", "/campaigns/click", h, json={"exposure_id": e})
                for h,e in [(woman, exp_ids[0]), (woman2, exp_ids[1]), (woman, exp_ids[0]), (woman2, exp_ids[1])]])
            async with sessions() as db:
                assert await db.scalar(select(func.count()).select_from(AdClickReceipt)) == 2
                assert await db.scalar(select(func.sum(AdBudgetLedger.amount_cents))) == 60
            metrics = await call("GET", f"/campaigns/{campaign['id']}/metrics", advertiser)
            assert metrics["clicks"] == 2 and metrics["impressions"] == 2 and metrics["ctr"] == 1
            assert metrics["billed_clicks"] == 1 and metrics["spend_cents"] == 60
            await call("PATCH", "/auth/me", woman, json={"gender": "man"})
            historical = await call("GET", f"/campaigns/{campaign['id']}/metrics?gender=woman", advertiser)
            assert historical["clicks"] == 2
            denied = await client.get(f"/campaigns/{campaign['id']}/metrics", headers=man)
            assert denied.status_code == 404
            await call("PATCH", f"/campaigns/{campaign['id']}", advertiser, json={"status": "paused"})
            # Simulate outbox failure after Mongo event write and before SQL ack.
            async with sessions() as db:
                receipts = list((await db.execute(select(AdClickReceipt))).scalars())
                for receipt in receipts:
                    receipt.synced = False
                await db.commit()
            await call("GET", f"/campaigns/{campaign['id']}/metrics", advertiser)
            assert await get_mongo().events.count_documents({"event_type": "ad_click"}) == 2
            print(json.dumps({"verified": ["gender targeting", "exposure frequency", "duplicate ingestion", "concurrent CPC budget",
                "outbox recovery", "historical gender", "ownership", "pause"], "clicks": 2, "charges": 1, "spend_cents": 60}))
    finally:
        await get_client().drop_database(name)
        settings.mongo_db = original_mongo
        await engine.dispose()
        async with admin_engine.begin() as connection:
            await connection.execute(text(f'DROP SCHEMA "{name}" CASCADE'))
        await admin_engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())
